<a href="https://colab.research.google.com/github/atchayabv/machine-learning/blob/main/E8122019_ML_CA1_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CA1-ML-Q2---** A hospital wants to develop a model to predict the severity of a 
patient's condition upon admission. The hospital has data on patients' demographics, medical history, and vital signs at admission. The hospital would like to use this information to predict whether the patient's condition is mild, moderate, or severe.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn import preprocessing

In [ ]:
data=pd.read_csv("/content/patient_data.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Age                         22 non-null     int64 
 1   Gender                      22 non-null     object
 2   Ethnicity                   22 non-null     object
 3   BMI                         22 non-null     int64 
 4   Blood Pressure (systolic)   22 non-null     int64 
 5   Blood Pressure (diastolic)  22 non-null     int64 
 6   Heart Rate                  22 non-null     int64 
 7   Respiratory Rate            22 non-null     int64 
 8   Oxygen Saturation Level     22 non-null     int64 
 9   Chronic Conditions          22 non-null     object
 10  Medications                 22 non-null     object
 11  Lab Test Results            22 non-null     object
 12  Chief Complaint             22 non-null     object
 13  Severity                    22 non-null     object
d

In [ ]:
data.head(5)

Age  Gender  Ethnicity  BMI  Blood Pressure (systolic)  \
0   45    Male  Caucasian   23                        120   
1   30  Female   Hispanic   27                        135   
2   65    Male    African   32                        150   
3   50  Female  Caucasian   29                        140   
4   28    Male      Asian   25                        115   

   Blood Pressure (diastolic)  Heart Rate  Respiratory Rate  \
0                          80          75                16   
1                          90          80                18   
2                         100          90                20   
3                          95          70                14   
4                          75          80                16   

   Oxygen Saturation Level Chronic Conditions     Medications  \
0                       98               None            None   
1                       95       Hypertension            None   
2                       92           Diabetes         Insulin   
3                       96               None  Blood thinners   
4                       97               None            None   

  Lab Test Results      Chief Complaint  Severity  
0           Normal           Chest Pain    Severe  
1     High Glucose             Headache  Moderate  
2  Abnormal Sodium  Shortness of Breath    Severe  
3           Normal           Chest Pain  Moderate  
4           Normal                Fever      Mild

In [ ]:
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'Severity
data['Severity']= label_encoder.fit_transform(data['Severity'])
data['Severity'].unique()

array([2, 1, 0])

In [ ]:
data.isnull().sum()

Age                           0
Gender                        0
Ethnicity                     0
BMI                           0
Blood Pressure (systolic)     0
Blood Pressure (diastolic)    0
Heart Rate                    0
Respiratory Rate              0
Oxygen Saturation Level       0
Chronic Conditions            0
Medications                   0
Lab Test Results              0
Chief Complaint               0
Severity                      0
dtype: int64

In [ ]:
q=data.select_dtypes(exclude=["object"])

In [ ]:
q.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         22 non-null     int64
 1   BMI                         22 non-null     int64
 2   Blood Pressure (systolic)   22 non-null     int64
 3   Blood Pressure (diastolic)  22 non-null     int64
 4   Heart Rate                  22 non-null     int64
 5   Respiratory Rate            22 non-null     int64
 6   Oxygen Saturation Level     22 non-null     int64
 7   Severity                    22 non-null     int64
dtypes: int64(8)
memory usage: 1.5 KB


In [ ]:
x=q.drop(columns="Severity")
y=q["Severity"]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
# Data Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(x_train)
X_test_scaled=scaler.transform(x_test)

In [ ]:
model=LogisticRegression()
model.fit(X_train_scaled,y_train)
predict=model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
#confusion matrix
print(confusion_matrix(y_test,predict))

[[2 0 2]
 [0 0 1]
 [0 1 1]]


In [ ]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         4
           1       0.00      0.00      0.00         1
           2       0.25      0.50      0.33         2

    accuracy                           0.43         7
   macro avg       0.42      0.33      0.33         7
weighted avg       0.64      0.43      0.48         7



In [ ]:
!pip install auto-sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 47.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 45.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 62.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.9/260.9 KB 25.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 98.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 KB 6.5 MB/s eta 0:00:00
  Created wheel for auto-sklearn: filename=auto_sklearn-0.15.0-py3-none-any.whl size=6641946 sha256=1d6d0b882c48a7a5063847630fa20b96dd65a2cd7e2a486ac61c7edc83d002e5

In [ ]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2955 sha256=f0c70750bcfd1419fb90ee5c32f98b5eb34ba803547195d32b7d29db752bf62f
  Stored in directory: /root/.cache/pip/wheels/f8/e0/3d/9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn


In [ ]:
import joblib

In [ ]:
!pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 62.3 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.2
    Uninstalling scikit-learn-0.24.2:
      Successfully uninstalled scikit-learn-0.24.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
auto-sklearn 0.15.0 requires scikit-learn<0.25.0,>=0.24.0, but you have scikit-learn 1.2.2 which is incompatible.


In [ ]:
import autosklearn.classification
l=autosklearn.classification.AutoSklearnClassifier(time_left_for_this_task=3*60,per_run_time_limit=30)
l.fit(X_train_scaled,y_train)
pred=l.predict(X_test_scaled)

In [ ]:
l.sprint_statistics

<bound method AutoSklearnEstimator.sprint_statistics of AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      per_run_time_limit=30, time_left_for_this_task=180)>

In [25]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
mae=mean_absolute_error(y_test,pred)
mse=mean_squared_error(y_test,pred)

In [26]:
print(mae)
print(mse)

1.0
1.8571428571428572


In [27]:
l.leaderboard()

rank  ensemble_weight           type  cost  duration
model_id                                                      
2            1             0.16  random_forest   0.2  2.702246
18           2             0.14  random_forest   0.2  1.689749
15           3             0.02  random_forest   0.4  1.887383
23           4             0.02  random_forest   0.4  2.580398
3            5             0.06  random_forest   0.6  2.289247
4            6             0.02  random_forest   0.6  1.638343
5            7             0.20            lda   0.6  0.888851
8            8             0.14  random_forest   0.6  2.482210
16           9             0.04  random_forest   0.6  1.617346
21          10             0.20    extra_trees   0.6  1.478159

In [28]:
from sklearn.svm import SVC
#support vector classifier
svc = SVC()
svc.fit(X_train_scaled,y_train)

SVC()

In [29]:
predict= model.predict(X_test_scaled)
predict

array([2, 2, 2, 2, 0, 1, 0])

In [30]:
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         4
           1       0.00      0.00      0.00         1
           2       0.25      0.50      0.33         2

    accuracy                           0.43         7
   macro avg       0.42      0.33      0.33         7
weighted avg       0.64      0.43      0.48         7

[[2 0 2]
 [0 0 1]
 [0 1 1]]
